- name: Create theme directory
  file:
    path: "{{ansible_user}}/.themes"
    state: directory

- name: Create icons directory
  file:
    path: "{{ansible_user}}/.icons"
    state: directory

- name: Copy themes
  copy:
    src: themes
    dest: "{{ansible_user}}/.themes"

- name: Copy Icons
  copy:
    src: icons
    dest: "{{ansible_user}}/.icons"

- name: Set Theme
  community.general.dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - key: /org/gnome/shell/extensions/user-theme/name
      value: "Dracula-black"
    - key: /org/gnome/desktop/interface/cursor-theme 
      value: 'Bibata-Original-Ice'
    - key: /org/gnome/desktop/interface/gtk-theme 
      value: 'Dracula-black'
    - key: /org/gnome/desktop/interface/icon-theme 
      value: 'Papirus'
