- name: Create theme directory
  file:
    path: "{{current_user}}/.themes"
    state: directory

- name: Create icons directory
  file:
    path: "{{current_user}}/.icons"
    state: directory

- name: Copy themes
  unarchive:
    src: "{{ item }}"
    dest: "{{current_user}}/.themes"
  with_fileglob: themes/*.tar.gz

- name: Copy icons
  unarchive:
    src: "{{ item }}"
    dest: "{{current_user}}/.themes"
  with_fileglob: icons/*.tar.gz

- name: Set Theme
  community.general.dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - key: /org/gnome/shell/extensions/user-theme/name
      value: "Dracula-black"
    - key: /org/gnome/desktop/interface/cursor-theme 
      value: 'Bibata-Original-Ice'
    - key: /org/gnome/desktop/interface/gtk-theme 
      value: 'Dracula-black'
    - key: /org/gnome/desktop/interface/icon-theme 
      value: 'Papirus'
