- hosts: laptop
  roles:
    - common
    - common-softwares

  pre_tasks:
    - name: Community Install
      shell: ansible-galaxy collection install {{ item }}
      args:
        creates: "{{home}}/.ansible/collections/ansible_collections/{{ item | replace('.', '/') }}"
      with_items:
        - community.general
        - ansible.posix

  post_tasks:
    - name: Pin Favorites
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{pinned_favorites}}"
        state: present
