- hosts: laptop
- name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
  include_vars:
    file: userVariables.yaml
    name: user_vars
  roles:
    - ide
    - dev-tools

  post_tasks:
    - name: Pin Favorites
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{pinned_favorites}}"
        state: present
