- hosts: laptop
  roles:
    - ide
    - dev-tools

  post_tasks:
    - name: Pin Favorites
      community.general.dconf:
        key: /org/gnome/shell/favorite-apps
        value: "{{pinned_favorites}}"
        state: present
