- name: Ansible user
  shell: export USER={{current_user}} && HOME={{home}}

- name: Add Apt Repositories
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ focal universe"
    state: present
  become: true
  become_user: root

# - name: Update and upgrade
#   apt: 
#     upgrade: "yes"
#     update_cache: "yes"

- name: Install bash apps
  apt:
    name: "{{bash_apps.common}}"
    state: present
  become: true
  become_user: root

- name: Install Auto-cpufreq
  shell: snap install auto-cpufreq
  become: true
  become_user: root

- name: Re-install Auto-cpufreq daemon
  shell: auto-cpufreq --remove && auto-cpufreq --install
  become_user: root
  become: true
   
- name: Create tmp download directory
  file:
    path: "{{download_location}}"
    state: directory

- import_tasks: gconf_settings.yml
# - import_tasks: gnome_extensions.yml
