- name: Install bash apps
  apt:
    name:
      [
        "nginx",
        "terminator",
        "git",
        "vim",
        "htop",
        "tldr",
        "exa",
      ]
    state: present
  become: true
  become_user: root

- name: Install NVM
  shell: "curl -o- -L {{nvm[\"download_url\"]}} | bash"
  args:
    creates: "{{home}}/.nvm"

- name: Install Node
  shell: >
    /bin/bash -c "source {{home}}/.nvm/nvm.sh && nvm install 14 && nvm alias default 14"

- name: Install Yarn
  shell: "curl -o- -L {{yarn[\"download_url\"]}} | bash"
  args:
    creates: "{{home}}/.yarn"
  ignore_errors: true

- name: Download MS Teams
  community.general.snap:
    name: teams
    state: present  

- name: Add MS Teams to Favorites
  set_fact:
    pinned_favorites: "{{pinned_favorites + ['teams.desktop'] }}"

- name: Copy vimrc
  copy:
    src: .vimrc
    dest: "{{home}}/.vimrc"

- name: Copy dev-help
  copy:
    src: .dev-help.sh
    dest: "{{home}}/.dev-help.sh"

- name: Custom prompt
  shell: cat roles/dev-tools/files/custom-prompt >> ~/.bashrc

- name: Modify file watches limit
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: 1048576
    state: present
  become: true
  become_user: root

- name: Add ssh key
  shell: "ssh-keygen -t rsa -b 4096 -f {{home}}/.ssh/id_rsa -q -N ''"
  args:
    creates: "{{home}}/.ssh/id_rsa"

- name: Copy ssh key to desktop
  copy:
    src: "{{home}}/.ssh/id_rsa.pub"
    dest: "{{home}}/Desktop/ssh-key"

- name: Install certificates
  copy:
    src: cert
    dest: '{{home}}/.local/share'

