- name: Install bash apps
  apt:
    name:
      [
        "nginx",
        "terminator",
        "git",
        "vim",
        "htop",
        "tldr",
        "exa",
      ]
    state: present
  become: true

- name: Install NVM
  shell: "curl -o- -L {{nvm[\"download_url\"]}} | bash"
  args:
    creates: "{{home}}/.nvm"

- name: Install Node
  shell: >
    /bin/bash -c "source {{home}}/.nvm/nvm.sh && nvm install 14 && nvm alias default 14"

- name: Install Yarn
  shell: "curl -o- -L {{yarn[\"download_url\"]}} | bash"
  args:
    creates: "{{home}}/.yarn"

- name: Download MS Teams
  get_url: url={{teams[\"download_url\"]}} dest={{download_location}}{{teams["destination"]}}

- name: Install MS Teams
  apt: deb={{download_location}}{{teams["destination"]}}
  become: true

- name: Add MS Teams to Favorites
  set_fact:
    pinned_favorites: "{{pinned_favorites + ['teams.desktop'] }}"

- name: Copy vimrc
  copy:
    src: .vimrc
    dest: "{{ansible_user_dir}}/.vimrc"

- name: Copy dev-help
  copy:
    src: dev-help.sh
    dest: "{{ansible_user_dir}}/dev-help.sh"

- name: Custom prompt
  shell: cat ../files/custom_prompt.sh >> ~/.bashrc

- name: Modify file watches limit
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: 1048576
    state: present

- name: Add ssh key
  shell: "ssh-keygen -t rsa -b 4096 -f {{ansible_user_dir}}/.ssh/id_rsa -q -N ''"
  args:
    creates: "{{ansible_user_dir}}/.ssh/id_rsa"

- name: Copy ssh key to desktop
  copy:
    src: "{{ansible_user_dir}}/.ssh/id_rsa.pub"
    dest: "{{ansible_user_dir}}/Desktop/ssh-key"

- name: Install certificates
  copy:
    src: cert
    dest: '{{ansible_user_dir}}/.local/share'

