- name: Install bash apps
  apt:
    name: "{{bash_apps.dev}}"
    state: present
  become: true
  become_user: root

- name: Install NVM
  shell: "curl -o- -L {{nvm[\"download_url\"]}} | bash"
  args:
    creates: "{{home}}/.nvm"

- name: Install Node
  shell: >
    /bin/bash -c "source {{home}}/.nvm/nvm.sh && nvm install 14 && nvm alias default 14"

- name: Install Yarn
  shell: "curl -o- -L {{yarn[\"download_url\"]}} | bash"
  args:
    creates: "{{home}}/.yarn"
  ignore_errors: true

- name: Download MS Teams
  community.general.snap:
    name: teams
    state: present
  become: true

- name: Add MS Teams to Favorites
  set_fact:
    pinned_favorites: "{{pinned_favorites + ['teams_teams.desktop'] }}"

- name: Copy vimrc
  copy:
    src: .vimrc
    dest: "{{home}}/.vimrc"

- name: Copy dev-help
  copy:
    src: .dev-help.sh
    dest: "{{home}}/.dev-help.sh"

- name: Custom prompt
  shell: cat roles/dev-tools/files/custom-prompt >> ~/.bashrc

- name: Modify file watches limit
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: 1048576
    state: present
  become: true
  become_user: root

- name: Add ssh key
  shell: "ssh-keygen -t rsa -b 4096 -f {{home}}/.ssh/id_rsa -q -N ''"
  args:
    creates: "{{home}}/.ssh/id_rsa"

- name: Copy ssh key to desktop
  copy:
    src: "{{home}}/.ssh/id_rsa.pub"
    dest: "{{home}}/Desktop/ssh-key"

- name: Install certificates
  copy:
    src: cert
    dest: '{{home}}/.local/share'

- name: Setup github config
  shell: git config --global user.name "{{github.name}}" && git config --global user.email "{{github.email}}"

- name: Open github to add new ssh keys
  shell: xdg-open https://github.com/settings/ssh/new

- name: Copy ssh key to clipboard
  shell: xclip -sel clip < {{home}}/.ssh/id_rsa.pub

- name: Wait for user to copy ssh key
  pause:
    prompt: "SSH key is copied to clipboard. Paste it in github, and then press enter"

- name: Confirm ssh key pasted
  pause:
    prompt: "Are you sure that ssh key is added to github"

- name: Create code directory
  file:
    path: "{{home}}/code"
    state: directory

- name: Clone repositories
  shell: git clone git@github.com:admitkard/{{item}}.git
  with_items:
    - akd_web
    - akd_integration_gateway
    - akd_ams
    - akd_iam
    - akd_scripts
    - akd_npm_packages
    - ansible-for-dev
    - ansible-deployment-scripts
    - akd_knowledge
  args:
    creates: "{{home}}/code/{{item}}"
    
